# Configure this Discovery Server
eureka:
  instance:
    hostname: localhost
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  #server:
    #enableSelfPreservation: false
server:
  port: 1111 # HTTP (Tomcat) port

# Spring properties
spring:
  application:
     name: discoveryserver
