eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://discoveryserver:1111/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
# HTTP Server
server:
  port: 4444

# Spring properties
spring:
  application:
     name: orderservice
